name: 'yeast_cen_intertwines'
logs_dir: 'logs'
simulation:
    script: 'scripts/run_yeast_intertwines.py'
    out_dir: 'results/simulations'
    replicates: 10 
    parameters_file: 'config/parameters.tsv'
analyses:
    create_maps:
        script: 'scripts/create_maps.py'
        out_dir: 'results/analyses/maps/raw'
        parameters:
            assembly: 'chains'
            bin_size: 2
            blocks: -100
    plot_maps:
        script: 'scripts/plot_maps.py'
        out_dir: 'results/analyses/maps/plots'
